//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aak.Shell.UI.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aak.Shell.UI.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Copy(_C) 的本地化字符串。
        /// </summary>
        public static string ApplicationCommands_Copy {
            get {
                return ResourceManager.GetString("ApplicationCommands_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut(_T) 的本地化字符串。
        /// </summary>
        public static string ApplicationCommands_Cut {
            get {
                return ResourceManager.GetString("ApplicationCommands_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste(_P) 的本地化字符串。
        /// </summary>
        public static string ApplicationCommands_Paste {
            get {
                return ResourceManager.GetString("ApplicationCommands_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scroll Down 的本地化字符串。
        /// </summary>
        public static string ScrollBar_LineDown {
            get {
                return ResourceManager.GetString("ScrollBar_LineDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scroll Left 的本地化字符串。
        /// </summary>
        public static string ScrollBar_LineLeft {
            get {
                return ResourceManager.GetString("ScrollBar_LineLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scroll Right 的本地化字符串。
        /// </summary>
        public static string ScrollBar_LineRight {
            get {
                return ResourceManager.GetString("ScrollBar_LineRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scroll Up 的本地化字符串。
        /// </summary>
        public static string ScrollBar_LineUp {
            get {
                return ResourceManager.GetString("ScrollBar_LineUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page Down 的本地化字符串。
        /// </summary>
        public static string ScrollBar_PageDown {
            get {
                return ResourceManager.GetString("ScrollBar_PageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page Left 的本地化字符串。
        /// </summary>
        public static string ScrollBar_PageLeft {
            get {
                return ResourceManager.GetString("ScrollBar_PageLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page Right 的本地化字符串。
        /// </summary>
        public static string ScrollBar_PageRight {
            get {
                return ResourceManager.GetString("ScrollBar_PageRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page Up 的本地化字符串。
        /// </summary>
        public static string ScrollBar_PageUp {
            get {
                return ResourceManager.GetString("ScrollBar_PageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scroll Here 的本地化字符串。
        /// </summary>
        public static string ScrollBar_ScrollHere {
            get {
                return ResourceManager.GetString("ScrollBar_ScrollHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom 的本地化字符串。
        /// </summary>
        public static string ScrollBar_ScrollToBottom {
            get {
                return ResourceManager.GetString("ScrollBar_ScrollToBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Edge 的本地化字符串。
        /// </summary>
        public static string ScrollBar_ScrollToLeftEnd {
            get {
                return ResourceManager.GetString("ScrollBar_ScrollToLeftEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Edge 的本地化字符串。
        /// </summary>
        public static string ScrollBar_ScrollToRightEnd {
            get {
                return ResourceManager.GetString("ScrollBar_ScrollToRightEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 的本地化字符串。
        /// </summary>
        public static string ScrollBar_ScrollToTop {
            get {
                return ResourceManager.GetString("ScrollBar_ScrollToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string WinSysButton_Close {
            get {
                return ResourceManager.GetString("WinSysButton_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize 的本地化字符串。
        /// </summary>
        public static string WinSysButton_Maximize {
            get {
                return ResourceManager.GetString("WinSysButton_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize 的本地化字符串。
        /// </summary>
        public static string WinSysButton_Minimize {
            get {
                return ResourceManager.GetString("WinSysButton_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore 的本地化字符串。
        /// </summary>
        public static string WinSysButton_Restore {
            get {
                return ResourceManager.GetString("WinSysButton_Restore", resourceCulture);
            }
        }
    }
}
